FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive


RUN dpkg --add-architecture i386 && \
    apt-get update

RUN apt-get install -y --no-install-recommends wine wine32 wine64 && \
    rm -rf /var/lib/apt/lists/*

# Configure Wine environment
ENV WINEARCH=win64
ENV WINEDEBUG=-all
ENV WINEPREFIX=/root/.wine
RUN wine wineboot --init

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openjdk-21-jre-headless && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

