services:
  rabbitmq:
    image: rabbitmq:3-management # Uses the image with the management UI
    ports:
      - "5672:5672" # Standard RabbitMQ port for message brokering
      - "15672:15672" # Port for the RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest # Default username
      RABBITMQ_DEFAULT_PASS: guest # Default password (change for production)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist data to a named volume

  worker:
      image: chesstango-tools-worker:latest
      depends_on:
        - rabbitmq
      environment:
        RABBIT_HOST: worker-rabbitmq-1
        ENGINE_CATALOG: /windows/catalog_wine
      volumes:
        - C:/java/projects/chess/chess-utils/engines:/windows # Persist data to a named volume

volumes:
  rabbitmq_data: # Define the named volume