FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive


RUN dpkg --add-architecture i386 && \
    apt-get update

RUN apt-get install -y --no-install-recommends wine wine32 wine64 && \
    rm -rf /var/lib/apt/lists/*

# Configure Wine environment
ENV WINEARCH=win64
ENV WINEDEBUG=-all
ENV WINEPREFIX=/root/.wine
RUN wine wineboot --init
